name: llm-mcts
dependencies:
  - python=3.11
  - pip
  # python libs
  - pytest
  - black
  - ipython
  # ml libs
  - numpy
  - pytorch
  - transformers
  - llama-cpp-python
  - outlines
  # graph libs
  - python-graphviz
